# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
    ]
